Repository mementai-internship/workswave-frontend, pull requests merged in 2024-10, with the labels that each got.

#23 [A조] 폴더명 수정
  src/components/BasicSetting/common/.gitkeep
  src/components/Common/Pagination.tsx
  src/components/Common/README.md
  src/components/Common/Title.tsx
  src/components/Common/Txt.tsx
  src/components/Home/.gitkeep
  src/components/ManagementBranch/.gitkeep
  src/components/common/README.md
  src/pages/basicSetting/BoardPage.tsx
Labels: hotfix, common

#34 [B조] Radix theme 루트 파일 세팅
  .gitignore
  src/App.tsx
  src/index.css
  src/main.tsx
  tailwind.config.js
Labels: chore, style, common

#35 [C조] 검색 공통 컴포넌트 / UI
  src/components/Common/ContactSearchInput.tsx
  src/components/Common/Title.tsx
  src/pages/home/HomePage.tsx
Labels: feat, style, C

#39 [FIX] Txt 색상 적용 정상화
  src/components/Common/Txt.tsx
Labels: fix, hotfix, common

#29 [B조] 회원 관리 페이지 / UI
  README.md
  package-lock.json
  package.json
  src/App.tsx
  src/components/Common/Pagination.tsx
  src/components/MemberManagement/MemberManagementDropdown.tsx
  src/components/MemberManagement/MemberManagementFilterBar.tsx
  src/components/MemberManagement/MemberManagementFilterButton.tsx
  src/components/MemberManagement/MemberManagementTable.tsx
  src/constants/memberManagementTableTitle.ts
  src/pages/memberManagement/MemberManagementPage.tsx
  src/utils/.gitkeep
  src/utils/calculateWorkPeriod.ts
Labels: feat, style, B

#42 [A조] Txt 컴포넌트 변경에 따른 sub title prop 기본 값 수정
  README.md
  package-lock.json
  package.json
  src/App.tsx
  src/components/Common/BasicSettingSubTitle.tsx
  src/components/Common/Pagination.tsx
  src/components/Common/Txt.tsx
  src/components/MemberManagement/MemberManagementDropdown.tsx
  src/components/MemberManagement/MemberManagementFilterBar.tsx
  src/components/MemberManagement/MemberManagementFilterButton.tsx
  src/components/MemberManagement/MemberManagementTable.tsx
  src/constants/memberManagementTableTitle.ts
  src/pages/memberManagement/MemberManagementPage.tsx
  src/utils/.gitkeep
  src/utils/calculateWorkPeriod.ts
Labels: fix, A

#44 [C조] 레이아웃 컴포넌트 / main padding 설정 hotfix
  src/layout/root.tsx
Labels: hotfix, style, C

#50 [C조] 로그인 페이지 / 로그인 UI
  src/pages/login/Login.tsx
  src/routes/index.tsx
Labels: feat, style, C

#46 [A조] 기본 설정 페이지 급여계산표 페이지 / UI
  src/components/BasicSetting/SalaryRange/SalaryRangeCalcRange.tsx
  src/components/BasicSetting/SalaryRange/SalaryRangeCalcResult.tsx
  src/components/BasicSetting/SalaryRange/SalaryRangeHeader.tsx
  src/components/BasicSetting/SalaryRange/SalaryRangeTable.tsx
  src/components/BasicSetting/SalaryRange/SalaryRangeTableTd.tsx
  src/constants/salaryRange.ts
  src/hooks/useSalaryRange.tsx
  src/layout/root.tsx
  src/models/salaryRange.model.ts
  src/pages/basicSetting/SalaryRangePage.tsx
  src/utils/calculatedSalaryRange.ts
Labels: feat, A

#52 [C조] 검색창 공통 컴포넌트 / UI
  src/components/Common/ContactSearchInput.tsx
  src/pages/home/HomePage.tsx
Labels: common

#56 [C조] TitleContainer 컴포넌트 개발
  src/components/Common/TitleContainer.tsx
Labels: feat, C, common

#49 [C조] 급여정산 페이지 / UI
  src/components/Common/ContactSearchInput.tsx
  src/components/SalarySettlement/SalaryPage/SalaryPageHeadderDropBox.tsx
  src/components/SalarySettlement/SalaryTable.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTable.tsx
  src/constants/SalarySettlementPage.ts
  src/layout/root.tsx
  src/models/salarySettlement.model.ts
  src/pages/home/HomePage.tsx
  src/pages/salarySettlement/SalarySettlementPage.tsx
  src/utils/changeSalarySettlementMonth.ts
Labels: feat, C

#62 [C조] 월 변경 컴포넌트 수정, constance 폴더 파일 대소문자 수정
  src/components/Common/ChangeMonth.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTable.tsx
  src/constants/salarySettlementPage.ts
  src/pages/salarySettlement/SalarySettlementPage.tsx
  src/utils/changeSalarySettlementMonth.ts
Labels: hotfix, C

#60 [B조] 회원 게시판 작성 페이지/UI
  package-lock.json
  package.json
  src/components/Common/Txt.tsx
  src/components/UserBoard/Write/BoardEditor.tsx
  src/layout/root.tsx
  src/pages/userBoard/write/BoardWritePage.tsx
  src/routes/index.tsx
Labels: feat, style, B

#71 [C조] 로그인 페이지 / 버그 해결 hotfix
  src/components/Common/TitleContainer.tsx
  src/layout/root.tsx
  src/pages/login/Login.tsx
Labels: hotfix, C

#66 [C조] 레이아웃 컴포넌트 / 헤더, 내비게이션 수정
  src/layout/Header/Header.tsx
  src/layout/Header/HeaderProfile.tsx
  src/layout/Navigation/Navigation.tsx
  src/layout/Navigation/const/index.ts
  src/layout/Navigation/constants/index.ts
Labels: refactor, C, common

#74 [A조] 기본 설정 페이지 flex 스타일 수정
  src/components/Common/BasicSettingSubTitle.tsx
Labels: style, A

#72 [B조] 회원 정보 페이지 / 기본 정보 테이블 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/Common/ContactSearchInput.tsx
  src/components/Common/Select.tsx
  src/components/MemberInfo/MemberBasicInfoDatePicker.tsx
  src/components/MemberInfo/MemberBasicInfoTable.tsx
  src/components/MemberInfo/MemberInfoButton.tsx
  src/components/MemberInfo/MemberInfoDropdownMenu.tsx
  src/components/MemberInfo/MemberInfoInput.tsx
  src/components/MemberManagement/MemberManagementTable.tsx
  src/pages/home/HomePage.tsx
  src/pages/memberManagement/MemberInfoPage.tsx
  src/pages/memberManagement/MemberManagementPage.tsx
  src/pages/userBoard/view/BoardViewPage.tsx
  src/pages/userBoard/write/BoardWritePage.tsx
  src/routes/index.tsx
Labels: feat, style, B

#57 [A조]기본 설정 페이지 게시판 설정 페이지 UI
  src/components/BasicSetting/BasicSettingBoard/BasicSettingBoardForm.tsx
  src/components/BasicSetting/BasicSettingBoard/BasicSettingBoardItem.tsx
  src/components/BasicSetting/BasicSettingBoard/BasicSettingBoardList.tsx
  src/constants/.gitkeep
  src/constants/authorities.ts
  src/constants/basicSetting.mock.ts
  src/hooks/useBasicSettingBoard.ts
  src/index.css
  src/models/basicSetting.model.ts
  src/models/user.model.ts
  src/pages/basicSetting/BoardPage.tsx
Labels: feat, A

#70 [A조] axios 환경 설정
  src/apis/axiosInstance.ts
  src/constants/url.ts
  src/utils/tokenUtils.ts
Labels: feat, A

#78 [C조] 문서관리 페이지 / 증명서 관리 페이지 UI 개발
  src/pages/documentManagement/ContractManagement.tsx
  src/pages/documentManagement/HolidayManagement.tsx
  src/pages/documentManagement/certificationManagement/CertificateManagement.tsx
  src/pages/documentManagement/certificationManagement/constants/index.ts
  src/routes/index.tsx
Labels: feat, style, C

#80 [B조] 회원게시판 라우팅 경로 수정
  package-lock.json
  package.json
  src/components/MemberInfo/MemberBasicInfoDatePicker.tsx
  src/components/MemberInfo/MemberBasicInfoTable.tsx
  src/components/MemberInfo/MemberInfoButton.tsx
  src/components/MemberInfo/MemberInfoDropdownMenu.tsx
  src/components/MemberInfo/MemberInfoInput.tsx
  src/components/MemberManagement/MemberManagementDropdown.tsx
  src/components/MemberManagement/MemberManagementFilterBar.tsx
  src/components/MemberManagement/MemberManagementFilterButton.tsx
  src/components/MemberManagement/MemberManagementTable.tsx
  src/components/UserBoard/View/UserBoardFilterBar/UserBoardFilterBar.tsx
  src/components/UserBoard/View/UserBoardFilterBar/UserBoardFilterBarDropdown/UserBoardFilterBarDropdown.tsx
  src/components/UserBoard/View/UserBoardTable/UserBoardTable.tsx
  src/components/UserBoard/View/UserBoardTable/UserBoardTableBody/UserBoardTableBody.tsx
  src/components/UserBoard/View/UserBoardTable/UserBoardTableHeader/UserBoardTableHeader.tsx
  src/components/UserBoard/Write/BoardEditor.tsx
  src/layout/Navigation/const/index.ts
  src/layout/Navigation/constants/index.ts
  src/pages/memberManagement/MemberInfoPage.tsx
  src/pages/memberManagement/MemberManagementPage.tsx
  src/pages/userBoard/view/BoardViewPage.tsx
  src/pages/userBoard/view/postNum/BoardViewPostPage.tsx
  src/pages/userBoard/write/BoardWritePage.tsx
  src/routes/index.tsx
Labels: chore, refactor, B

#81 [B조] PR 머지 브랜치 잘못 설정 revert
  package-lock.json
  package.json
  src/components/MemberInfo/MemberBasicInfoDatePicker.tsx
  src/components/MemberInfo/MemberBasicInfoTable.tsx
  src/components/MemberInfo/MemberInfoButton.tsx
  src/components/MemberInfo/MemberInfoDropdownMenu.tsx
  src/components/MemberInfo/MemberInfoInput.tsx
  src/components/MemberManagement/MemberManagementDropdown.tsx
  src/components/MemberManagement/MemberManagementFilterBar.tsx
  src/components/MemberManagement/MemberManagementFilterButton.tsx
  src/components/MemberManagement/MemberManagementTable.tsx
  src/components/UserBoard/View/UserBoardFilterBar/UserBoardFilterBar.tsx
  src/components/UserBoard/View/UserBoardFilterBar/UserBoardFilterBarDropdown/UserBoardFilterBarDropdown.tsx
  src/components/UserBoard/View/UserBoardTable/UserBoardTable.tsx
  src/components/UserBoard/View/UserBoardTable/UserBoardTableBody/UserBoardTableBody.tsx
  src/components/UserBoard/View/UserBoardTable/UserBoardTableHeader/UserBoardTableHeader.tsx
  src/components/UserBoard/Write/BoardEditor.tsx
  src/layout/Navigation/const/index.ts
  src/layout/Navigation/constants/index.ts
  src/pages/memberManagement/MemberInfoPage.tsx
  src/pages/memberManagement/MemberManagementPage.tsx
  src/pages/userBoard/view/BoardViewPage.tsx
  src/pages/userBoard/view/postNum/BoardViewPostPage.tsx
  src/pages/userBoard/write/BoardWritePage.tsx
  src/routes/index.tsx
Labels: fix, B

#83 [B조] 회원게시판 라우팅 경로 변경
  src/components/Common/TitleContainer.tsx
  src/layout/Header/Header.tsx
  src/layout/Header/HeaderProfile.tsx
  src/layout/Navigation/Navigation.tsx
  src/layout/Navigation/constants/index.ts
  src/routes/index.tsx
Labels: refactor, B

#88 [C조] 출퇴근 관리 너비 수정
  src/pages/workManagement/WorkManagementPage.tsx
  src/routes/index.tsx
Labels: hotfix

#93 [C조] 휴무 캘린더 UI 구현
  package-lock.json
  package.json
  src/components/Common/ChangeMonth.tsx
  src/components/HolidayCalendar/ChangeWeek.tsx
  src/components/HolidayCalendar/HolidayCalendar.tsx
  src/components/SalarySettlement/SalaryPage/CategoryDropBox.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTable.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTableHeader.tsx
  src/hooks/SalarySettlement/useFilteredEmployees.ts
  src/hooks/SalarySettlement/useSalarySummary.ts
  src/hooks/SalarySettlement/useSettlementEmployee.ts
  src/layout/Navigation/Navigation.tsx
  src/models/salarySettlement.model.ts
  src/pages/holidayCalendar/HolidayCalendarPage.tsx
  src/pages/salarySettlement/SalarySettlementPage.tsx
  src/routes/index.tsx
  src/utils/calculateSettlementTotal.ts
Labels: feat, C

#77 [A조] A dev에서 dev로 푸시
  src/apis/salaryRange.api.ts
  src/components/BasicSetting/BasicSettingBoard/BasicSettingBoardForm.tsx
  src/components/BasicSetting/BasicSettingBoard/BasicSettingBoardItem.tsx
  src/components/BasicSetting/BasicSettingBoard/BasicSettingBoardList.tsx
  src/components/BasicSetting/SalaryRange/SalaryRangeCalcRange.tsx
  src/components/BasicSetting/SalaryRange/SalaryRangeCalcResult.tsx
  src/components/BasicSetting/SalaryRange/SalaryRangeHeader.tsx
  src/components/BasicSetting/SalaryRange/SalaryRangeTable.tsx
  src/components/BasicSetting/SalaryRange/SalaryRangeTableTd.tsx
  src/components/BasicSetting/common/.gitkeep
  src/components/Common/BasicSettingSubTitle.tsx
  src/constants/.gitkeep
  src/constants/authorities.ts
  src/constants/basicSetting.mock.ts
  src/constants/salaryRange.ts
  src/hooks/apis/useFetchSalaryRange.ts
  src/hooks/useBasicSettingBoard.ts
  src/hooks/useSalaryRange.tsx
  src/index.css
  src/models/basicSetting.model.ts
  src/models/salaryRange.model.ts
  src/models/user.model.ts
  src/pages/basicSetting/BoardPage.tsx
  src/pages/basicSetting/SalaryRangePage.tsx
  tsconfig.tsbuildinfo
Labels: feat

#90 [C조] 헤더, 내비게이션 유저 mockData 권한 수정 hotfix
  src/layout/Header/Header.tsx
  src/layout/Navigation/Navigation.tsx
Labels: hotfix, C, common

#87 [B조] B_dev에서 dev로 푸시
  package-lock.json
  package.json
  src/components/Common/Select.tsx
  src/components/MemberInfo/MemberBasicInfoDatePicker.tsx
  src/components/MemberInfo/MemberBasicInfoTable.tsx
  src/components/MemberInfo/MemberInfoButton.tsx
  src/components/MemberInfo/MemberInfoDropdownMenu.tsx
  src/components/MemberInfo/MemberInfoInput.tsx
  src/components/MemberManagement/MemberManagementDropdown.tsx
  src/components/MemberManagement/MemberManagementFilterBar.tsx
  src/components/MemberManagement/MemberManagementFilterButton.tsx
  src/components/MemberManagement/MemberManagementTable.tsx
  src/components/UserBoard/View/UserBoardFilterBar/UserBoardFilterBar.tsx
  src/components/UserBoard/View/UserBoardFilterBar/UserBoardFilterBarDropdown/UserBoardFilterBarDropdown.tsx
  src/components/UserBoard/View/UserBoardTable/UserBoardTable.tsx
  src/components/UserBoard/View/UserBoardTable/UserBoardTableBody/UserBoardTableBody.tsx
  src/components/UserBoard/View/UserBoardTable/UserBoardTableHeader/UserBoardTableHeader.tsx
  src/components/UserBoard/Write/BoardEditor.tsx
  src/layout/Navigation/const/index.ts
  src/layout/Navigation/constants/index.ts
  src/pages/memberManagement/MemberInfoPage.tsx
  src/pages/memberManagement/MemberManagementPage.tsx
  src/pages/userBoard/view/BoardViewPage.tsx
  src/pages/userBoard/view/postNum/BoardViewPostPage.tsx
  src/pages/userBoard/write/BoardWritePage.tsx
  src/routes/index.tsx
Labels: B

#96 [C조] C_dev에서 dev로 Push
  package-lock.json
  package.json
  src/components/Common/ChangeMonth.tsx
  src/components/HolidayCalendar/ChangeWeek.tsx
  src/components/HolidayCalendar/HolidayCalendar.tsx
  src/components/SalarySettlement/SalaryPage/CategoryDropBox.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTable.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTableHeader.tsx
  src/components/WorkManagement/Commute/Commute.tsx
  src/components/WorkManagement/Commute/CommuteTableRows.tsx
  src/components/WorkManagement/PartTime/PartTime.tsx
  src/components/WorkManagement/PartTime/PartTimeTableRows.tsx
  src/components/WorkManagement/WorkFilterLayout.tsx
  src/components/WorkManagement/WorkHeader.tsx
  src/components/WorkManagement/WorkSelect.tsx
  src/constants/salarySettlementPage.ts
  src/constants/workManagementTable/workSelect.mock.ts
  src/constants/workManagementTable/workTable.mock.ts
  src/constants/workManagementTable/workTable.ts
  src/hooks/SalarySettlement/useFilteredEmployees.ts
  src/hooks/SalarySettlement/useSalarySummary.ts
  src/hooks/SalarySettlement/useSettlementEmployee.ts
  src/layout/root.tsx
  src/models/salarySettlement.model.ts
  src/models/workManagement/work.model.ts
  src/pages/documentManagement/ContractManagement.tsx
  src/pages/documentManagement/HolidayManagement.tsx
  src/pages/documentManagement/certificationManagement/CertificateManagement.tsx
  src/pages/documentManagement/certificationManagement/constants/index.ts
  src/pages/holidayCalendar/HolidayCalendarPage.tsx
  src/pages/login/Login.tsx
  src/pages/salarySettlement/SalarySettlementPage.tsx
  src/pages/workManagement/WorkManagementPage.tsx
  src/routes/index.tsx
  src/utils/calculateSettlementTotal.ts
  src/utils/changeSalarySettlementMonth.ts
Labels: C

#91 [B조] 공통 컴포넌트 SelectBox 수정
  src/components/Common/Select.tsx
Labels: hotfix, B, common

#100 [B조] 기본설정 게시판 설정 내비게이션 경로 수정
  src/routes/index.tsx
Labels: hotfix, refactor, B

#101 [C조] 증명서관리 페이지 / 공통컴포넌트 적용 및 너비 수정
  src/pages/documentManagement/certificationManagement/CertificateManagement.tsx
  src/pages/documentManagement/certificationManagement/constants/index.ts
Labels: hotfix, style, C

#107 [A조] 기본 설정의 근무 설정 페이지 UI 제작
  package-lock.json
  package.json
  src/components/BasicSetting/WorkingSetting/SetAutoOT.tsx
  src/components/BasicSetting/WorkingSetting/SetBasicSalary.tsx
  src/components/BasicSetting/WorkingSetting/SetBasicWork.tsx
  src/components/BasicSetting/WorkingSetting/SetHoliday.tsx
  src/components/BasicSetting/WorkingSetting/SetIP.tsx
  src/components/BasicSetting/WorkingSetting/SetOT.tsx
  src/components/BasicSetting/WorkingSetting/SetPart/SetPart.tsx
  src/components/BasicSetting/WorkingSetting/SetPart/SetPartForm.tsx
  src/components/BasicSetting/WorkingSetting/SetPart/SetPartItem.tsx
  src/components/BasicSetting/WorkingSetting/SetWeekendSalary.tsx
  src/components/BasicSetting/WorkingSetting/WorkingSettingTitle.tsx
  src/constants/pickColors.ts
  src/constants/workingSetting.mock.ts
  src/hooks/apis/.gitkeep
  src/hooks/apis/useWorkingSettingPart.ts
  src/index.css
  src/models/workingSetting.model.ts
  src/pages/basicSetting/WorkingPage.tsx
  src/utils/adaptTaskToColor.ts
  src/utils/getTimes.ts
Labels: style, A

#108 [C조] C_dev 에서 dev로 push
  src/pages/documentManagement/certificationManagement/CertificateManagement.tsx
  src/pages/documentManagement/certificationManagement/constants/index.ts
Labels: C

#110 [C조] 급여정산, 휴무캘린더 CSS 수정
  src/components/SalarySettlement/SalaryTable/SalaryTable.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTableHeader.tsx
  src/pages/holidayCalendar/HolidayCalendarPage.tsx
  src/pages/salarySettlement/SalarySettlementPage.tsx
Labels: hotfix, style, C

#112 [C조] 환경변수 관리 hotfix
  .gitignore
  src/apis/axiosInstance.ts
  src/constants/url.ts
Labels: hotfix, C

#116 [C조] 내비게이션 / 회원게시판탭 css 적용되지 않던 이슈 해결
  src/layout/Navigation/constants/index.ts
  src/routes/index.tsx
Labels: hotfix, style, C, common

#123 [C조] 공통 컴포넌트 Select 수정
  src/components/Common/Select.tsx
Labels: hotfix, common

#121 [C조] 검색 공통 컴포넌트 수정
  src/components/Common/ContactSearchInput.tsx
Labels: hotfix

#124 [C조 dev] 급여명세 페이지 버그 수정
  .gitignore
  src/components/Common/ChangeMonth.tsx
  src/components/HolidayCalendar/ChangeWeek.tsx
  src/components/SalarySettlement/SalaryPage/CategoryDropBox.tsx
  src/components/SalarySettlement/SalaryPage/CategorySelect.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTable.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTableBody.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTableFooter.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTableHeader.tsx
  src/components/WorkManagement/WorkHeader.tsx
  src/constants/salarySettlement.ts
  src/constants/salarySettlementPage.ts
  src/hooks/SalarySettlement/useSettlementEmployee.ts
  src/index.css
  src/models/salarySettlement.model.ts
  src/pages/holidayCalendar/HolidayCalendarPage.tsx
  src/pages/salarySettlement/SalarySettlementPage.tsx
  src/utils/calculatePaymentDate.ts
Labels: refactor, C

#132 [A조] 스타일 undefined 들어가던 것 수정
  .gitignore
  src/apis/axiosInstance.ts
  src/components/Common/BasicSettingSubTitle.tsx
  src/components/Common/ChangeMonth.tsx
  src/components/Common/ContactSearchInput.tsx
  src/components/Common/Select.tsx
  src/components/HolidayCalendar/ChangeWeek.tsx
  src/components/SalarySettlement/SalaryPage/CategoryDropBox.tsx
  src/components/SalarySettlement/SalaryPage/CategorySelect.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTable.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTableBody.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTableFooter.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTableHeader.tsx
  src/components/WorkManagement/WorkHeader.tsx
  src/constants/salarySettlement.ts
  src/constants/salarySettlementPage.ts
  src/constants/url.ts
  src/hooks/SalarySettlement/useSettlementEmployee.ts
  src/index.css
  src/layout/Navigation/constants/index.ts
  src/models/salarySettlement.model.ts
  src/pages/holidayCalendar/HolidayCalendarPage.tsx
  src/pages/salarySettlement/SalarySettlementPage.tsx
  src/routes/index.tsx
  src/utils/calculatePaymentDate.ts
Labels: style, A

#128 [B조 common] 페이지네이션 수정
  src/components/Common/Pagination.tsx
  src/components/UserBoard/View/UserBoardTable/UserBoardTable.tsx
  src/pages/memberManagement/MemberManagementPage.tsx
  src/pages/workManagement/WorkManagementPage.tsx
Labels: fix, B, common

#127 [B조] 회원 정보 페이지 / 계약 정보 테이블 구현
  src/components/Common/Select.tsx
  src/components/MemberInfo/MemberBasicInfoTable.tsx
  src/components/MemberInfo/MemberInfoCommon/ContractInfoBar.tsx
  src/components/MemberInfo/MemberInfoCommon/ContractInfoCheckbox.tsx
  src/components/MemberInfo/MemberInfoCommon/MemberBasicInfoDatePicker.tsx
  src/components/MemberInfo/MemberInfoCommon/MemberInfoButton.tsx
  src/components/MemberInfo/MemberInfoCommon/MemberInfoButtonBar.tsx
  src/components/MemberInfo/MemberInfoCommon/MemberInfoDropdownMenu.tsx
  src/components/MemberInfo/MemberInfoCommon/MemberInfoInput.tsx
  src/components/MemberInfo/MemberInfoInput.tsx
  src/components/MemberInfo/SalaryContractTable.tsx
  src/components/MemberInfo/WorkContractTable.tsx
  src/components/MemberInfo/WorkContractTableCell.tsx
  src/constants/memberInfoTable.ts
  src/constants/memberManagementTableTitle.ts
  src/pages/memberManagement/MemberInfoPage.tsx
Labels: feat, style, B

#137 [B조] 회원관리 페이지 / 리뉴얼 UI 수정
  src/components/MemberManagement/MemberManagementFilterBar.tsx
  src/components/MemberManagement/MemberManagementTable.tsx
  src/components/MemberManagement/MemberManagementTableCell.tsx
  src/components/UserBoard/View/PostNum/PostViewerBody/PostViewerBody.tsx
  src/components/UserBoard/View/PostNum/PostViewerComment/PostViewerComment.tsx
  src/components/UserBoard/View/PostNum/PostViewerHeader/PostViewerHeader.tsx
  src/constants/memberManagementTableTitle.ts
  src/pages/memberManagement/MemberManagementPage.tsx
  src/pages/userBoard/view/postNum/BoardViewPostPage.tsx
Labels: feat, style, refactor, B

#133 [C조] 로그인 구현
  package-lock.json
  package.json
  src/apis/auth.api.ts
  src/apis/axiosInstance.ts
  src/apis/login.api.ts
  src/apis/logout.api.ts
  src/hooks/apis/useGetCurrentUser.ts
  src/layout/Header/Header.tsx
  src/layout/Header/HeaderProfile.tsx
  src/layout/Navigation/Navigation.tsx
  src/layout/Navigation/constants/index.ts
  src/layout/root.tsx
  src/models/login.model.ts
  src/models/user.model.ts
  src/pages/login/Login.tsx
  src/store/authAtoms.ts
  vite.config.ts
Labels: feat, C

#139 [C조 dev]
  package-lock.json
  package.json
  src/apis/auth.api.ts
  src/apis/axiosInstance.ts
  src/apis/login.api.ts
  src/apis/logout.api.ts
  src/hooks/apis/useGetCurrentUser.ts
  src/layout/Header/Header.tsx
  src/layout/Header/HeaderProfile.tsx
  src/layout/Navigation/Navigation.tsx
  src/layout/Navigation/constants/index.ts
  src/layout/root.tsx
  src/models/login.model.ts
  src/models/user.model.ts
  src/pages/login/Login.tsx
  src/store/authAtoms.ts
  vite.config.ts
Labels: feat, C

#144 [C조] 회원관리 - 최고/지점관리자 설정 페이지 UI 개발
  src/pages/memberManagement/MemberManagementPage.tsx
  src/pages/memberManagement/SuperManagerSetting.tsx
  src/routes/index.tsx
Labels: feat, style, C

#149 [A조] 지점설정 페이지, 삭제지점관리 페이지 / UI
  package-lock.json
  package.json
  src/apis/auth.api.ts
  src/apis/axiosInstance.ts
  src/apis/login.api.ts
  src/apis/logout.api.ts
  src/apis/salary-bracket.ts
  src/components/Common/Pagination.tsx
  src/components/Common/Select.tsx
  src/components/MemberInfo/MemberBasicInfoTable.tsx
  src/components/MemberInfo/MemberInfoCommon/ContractInfoBar.tsx
  src/components/MemberInfo/MemberInfoCommon/ContractInfoCheckbox.tsx
  src/components/MemberInfo/MemberInfoCommon/MemberBasicInfoDatePicker.tsx
  src/components/MemberInfo/MemberInfoCommon/MemberInfoButton.tsx
  src/components/MemberInfo/MemberInfoCommon/MemberInfoButtonBar.tsx
  src/components/MemberInfo/MemberInfoCommon/MemberInfoDropdownMenu.tsx
  src/components/MemberInfo/MemberInfoCommon/MemberInfoInput.tsx
  src/components/MemberInfo/MemberInfoInput.tsx
  src/components/MemberInfo/SalaryContractTable.tsx
  src/components/MemberInfo/WorkContractTable.tsx
  src/components/MemberInfo/WorkContractTableCell.tsx
  src/components/MemberManagement/MemberManagementFilterBar.tsx
  src/components/MemberManagement/MemberManagementTable.tsx
  src/components/MemberManagement/MemberManagementTableCell.tsx
  src/components/OfficeSetting/OfficeSettingCreate.tsx
  src/components/OfficeSetting/OfficeSettingCreateRow.tsx
  src/components/OfficeSetting/OfficeSettingFileUpload.tsx
  src/components/OfficeSetting/OfficeSettingHeader.tsx
  src/components/OfficeSetting/OfficeSettingTable.tsx
  src/components/OfficeSetting/OfficeSettingTableCell.tsx
  src/components/UserBoard/View/PostNum/PostViewerBody/PostViewerBody.tsx
  src/components/UserBoard/View/PostNum/PostViewerComment/PostViewerComment.tsx
  src/components/UserBoard/View/PostNum/PostViewerHeader/PostViewerHeader.tsx
  src/components/UserBoard/View/UserBoardTable/UserBoardTable.tsx
  src/constants/memberInfoTable.ts
  src/constants/memberManagementTableTitle.ts
  src/constants/officeSettingTableTitle.ts
  src/hooks/apis/useGetCurrentUser.ts
  src/layout/Header/Header.tsx
  src/layout/Header/HeaderProfile.tsx
  src/layout/Navigation/Navigation.tsx
  src/layout/Navigation/constants/index.ts
  src/layout/root.tsx
  src/models/login.model.ts
  src/models/officeSetting.model.ts
  src/models/user.model.ts
  src/pages/login/Login.tsx
  src/pages/memberManagement/MemberInfoPage.tsx
  src/pages/memberManagement/MemberManagementPage.tsx
  src/pages/officeSetting/ManagementDeleteOfficePage.tsx
  src/pages/officeSetting/ManagementOfficePage.tsx
  src/pages/userBoard/view/postNum/BoardViewPostPage.tsx
  src/pages/workManagement/WorkManagementPage.tsx
  src/routes/index.tsx
  src/store/authAtoms.ts
  vite.config.ts
Labels: feat, A

#146 [C조] 간편메뉴 / 권한: 일반사원
  src/layout/Header/Header.tsx
  src/pages/simpleMenu/SimpleMenuPage.tsx
  src/routes/index.tsx
Labels: feat, style, C

#147 [C조] 휴무 캘린더 일정 등록, 상세 보기 구현
  src/components/HolidayCalendar/ChangeWeek.tsx
  src/components/HolidayCalendar/EmployeeHolidayRegisterModal.tsx
  src/components/HolidayCalendar/HolidayCalendar.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTable.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTableBody.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTableFooter.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTableHeader.tsx
  src/pages/holidayCalendar/HolidayCalendarPage.tsx
  src/pages/salarySettlement/SalarySettlementPage.tsx
  vercel.json
Labels: feat, C

#151 [C조] 로그아웃시 레이아웃 컴포넌트 리렌더링 안되던 이슈 해결
  src/layout/Header/Header.tsx
  src/layout/Header/HeaderProfile.tsx
  src/store/authAtoms.ts
Labels: fix, C

#154 [C조 dev] C_dev 에서 dev로 merge
  src/components/HolidayCalendar/ChangeWeek.tsx
  src/components/HolidayCalendar/EmployeeHolidayRegisterModal.tsx
  src/components/HolidayCalendar/HolidayCalendar.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTable.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTableBody.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTableFooter.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTableHeader.tsx
  src/layout/Header/Header.tsx
  src/layout/Header/HeaderProfile.tsx
  src/pages/holidayCalendar/HolidayCalendarPage.tsx
  src/pages/memberManagement/MemberManagementPage.tsx
  src/pages/memberManagement/SuperManagerSetting.tsx
  src/pages/salarySettlement/SalarySettlementPage.tsx
  src/pages/simpleMenu/SimpleMenuPage.tsx
  src/routes/index.tsx
  src/store/authAtoms.ts
  vercel.json
Labels: C

#158 [B조] 회원관리 리스트 페이지 / API 연결
  package-lock.json
  package.json
  src/apis/auth.api.ts
  src/apis/authAxiosInstance.ts
  src/apis/axiosInstance.ts
  src/apis/login.api.ts
  src/apis/logout.api.ts
  src/apis/user-management.api.ts
  src/components/MemberInfo/MemberBasicInfoTable.tsx
  src/components/MemberInfo/SalaryContractTable.tsx
  src/components/MemberManagement/MemberManagementTable.tsx
  src/components/MemberManagement/MemberManagementTableCell.tsx
  src/constants/queryKeys.ts
  src/hooks/apis/useGetCurrentUser.ts
  src/hooks/apis/useUserManagement.ts
  src/layout/Header/Header.tsx
  src/layout/Header/HeaderProfile.tsx
  src/layout/Navigation/Navigation.tsx
  src/layout/Navigation/constants/index.ts
  src/layout/root.tsx
  src/models/login.model.ts
  src/models/user-management.model.ts
  src/models/user.model.ts
  src/pages/login/Login.tsx
  src/pages/memberManagement/MemberManagementPage.tsx
  src/store/authAtoms.ts
  vite.config.ts
Labels: feat, B

#161 [B조 dev] B_dev에서 dev로 merge
  .prettierrc
  src/apis/auth.api.ts
  src/apis/authAxiosInstance.ts
  src/apis/axiosInstance.ts
  src/apis/login.api.ts
  src/apis/user-management.api.ts
  src/components/Common/Select.tsx
  src/components/DayoffManagement/DayoffManagementFilterbar/DayoffManagementFilterbar.tsx
  src/components/DayoffManagement/DayoffManagementFilterbar/WeekSelector.tsx
  src/components/DayoffManagement/DayoffManagementHeader.tsx
  src/components/DayoffManagement/DayoffManagementList/DayoffManagementTable.tsx
  src/components/DayoffManagement/DayoffManagementList/DayoffManagementTableItem.tsx
  src/components/MemberInfo/DocsDraftTable.tsx
  src/components/MemberInfo/DocsRegisterTable.tsx
  src/components/MemberInfo/DocsTable.tsx
  src/components/MemberInfo/MemberBasicInfoTable.tsx
  src/components/MemberInfo/MemberInfoCommon/ContractInfoCheckbox.tsx
  src/components/MemberInfo/MemberInfoCommon/MemberInfoButtonBar.tsx
  src/components/MemberInfo/MemberInfoCommon/RegisterDocsInput.tsx
  src/components/MemberInfo/MemberInfoCommon/WrittenContractCheckBox.tsx
  src/components/MemberInfo/SalaryContractTable.tsx
  src/components/MemberInfo/WorkContractTable.tsx
  src/components/MemberInfo/WorkContractTableCell.tsx
  src/components/MemberInfo/WrittenContractTable.tsx
  src/components/MemberManagement/MemberManagementTable.tsx
  src/components/MemberManagement/MemberManagementTableCell.tsx
  src/constants/queryKeys.ts
  src/hooks/DayoffManagement/useWeekSelector.ts
  src/hooks/apis/useUserManagement.ts
  src/models/user-management.model.ts
  src/pages/dayoffManagement/DayoffManagement.tsx
  src/pages/documentManagement/certificationManagement/CertificateManagement.tsx
  src/pages/memberManagement/MemberInfoPage.tsx
  src/pages/memberManagement/MemberManagementPage.tsx
  src/routes/index.tsx
Labels: feat, style, B

#138 [A조] 기본설정 페이지 임금설정 페이지 / UI
  src/components/BasicSetting/Wage/WageAutoSettingRow.tsx
  src/components/BasicSetting/Wage/WageCalculate.tsx
  src/components/BasicSetting/Wage/WageContainer.tsx
  src/components/BasicSetting/Wage/WageFieldset.tsx
  src/components/BasicSetting/Wage/WageItem.tsx
  src/components/BasicSetting/Wage/WageList.tsx
  src/components/BasicSetting/Wage/WageSelect.tsx
  src/hooks/useHourlyRange.ts
  src/hooks/useSalaryRange.ts
  src/hooks/useWageSetting.ts
  src/models/wageSetting.model.ts
  src/pages/basicSetting/WagePage.tsx
  src/utils/validateOnBlurForInputNumber.ts
Labels: feat, A

#166 [B조 dev] 코드 리뷰 반영 API 로직 수정
  src/apis/auth.api.ts
  src/apis/axiosInstance.ts
  src/components/MemberInfo/MemberInfoCommon/MemberInfoButtonBar.tsx
  src/hooks/apis/useGetCurrentUser.ts
  src/hooks/apis/useUserManagement.ts
  src/layout/Header/HeaderProfile.tsx
  src/pages/memberManagement/MemberInfoPage.tsx
  src/pages/memberManagement/MemberManagementPage.tsx
  src/pages/memberManagement/SuperManagerSetting.tsx
  src/store/authAtoms.ts
  tsconfig.tsbuildinfo
Labels: style, refactor, B

#164 [B조] OT관리 UI 제작
  src/components/OtManagement/OtManagementFilterbar/OtManagementManagementFilterbar.tsx
  src/components/OtManagement/OtManagementFilterbar/WeekSelector.tsx
  src/components/OtManagement/OtManagementHeader.tsx
  src/components/OtManagement/OtManagementList/OtManagementTable.tsx
  src/components/OtManagement/OtManagementList/OtManagementTableItem.tsx
  src/pages/otManagement/OtManagementPage.tsx
  src/routes/index.tsx
Labels: feat, style, B

#170 [A조] 근무설정 페이지 UI 및 API 연동
  src/apis/basic-setting-part.api.ts
  src/apis/branches.api.ts
  src/apis/parts.api.ts
  src/apis/work-policies.ts
  src/components/BasicSetting/WorkingSetting/SetAutoOT.tsx
  src/components/BasicSetting/WorkingSetting/SetBasicSalary.tsx
  src/components/BasicSetting/WorkingSetting/SetBasicWork.tsx
  src/components/BasicSetting/WorkingSetting/SetBasicWorkItem.tsx
  src/components/BasicSetting/WorkingSetting/SetHoliday.tsx
  src/components/BasicSetting/WorkingSetting/SetOT.tsx
  src/components/BasicSetting/WorkingSetting/SetPart/SetPart.tsx
  src/components/BasicSetting/WorkingSetting/SetPart/SetPartForm.tsx
  src/components/BasicSetting/WorkingSetting/SetPart/SetPartItem.tsx
  src/components/BasicSetting/WorkingSetting/SetWeekendSalary.tsx
  src/components/BasicSetting/WorkingSetting/TimeRangeSelector.tsx
  src/components/BasicSetting/WorkingSetting/WorkingSettingTitle.tsx
  src/components/OfficeSetting/OfficeSettingCreate.tsx
  src/components/OfficeSetting/OfficeSettingCreateRow.tsx
  src/components/OfficeSetting/OfficeSettingFileUpload.tsx
  src/components/OfficeSetting/OfficeSettingHeader.tsx
  src/components/OfficeSetting/OfficeSettingTable.tsx
  src/constants/workingSetting.mock.ts
  src/hooks/apis/useBranches.ts
  src/hooks/apis/useParts.ts
  src/hooks/apis/useWorkPolicies.ts
  src/hooks/apis/useWorkingSettingPart.ts
  src/models/parts.ts
  src/models/work-policies.ts
  src/models/workingSetting.model.ts
  src/pages/basicSetting/WorkingPage.tsx
  src/pages/officeSetting/ManagementDeleteOfficePage.tsx
  src/pages/officeSetting/ManagementOfficePage.tsx
  src/utils/getTimes.ts
Labels: feat, A

#174 [B조 dev] 회원관리 페이지 / 페이지네이션 적용, UI 수정
  src/apis/user-management.api.ts
  src/components/MemberInfo/MemberInfoCommon/MemberInfoDropdownMenu.tsx
  src/components/MemberManagement/MemberManagementFilterBar.tsx
  src/components/MemberManagement/MemberManagementTable.tsx
  src/components/MemberManagement/MemberManagementTableCell.tsx
  src/constants/memberManagementTableTitle.ts
  src/hooks/apis/useUserManagement.ts
  src/pages/memberManagement/MemberManagementPage.tsx
Labels: style, refactor, B

#177 [A조 dev] 지점설정 페이지 버그 수정
  src/components/OfficeSetting/OfficeSettingCreate.tsx
  src/components/OfficeSetting/OfficeSettingTableCell.tsx
  src/hooks/useSalaryRange.ts
  src/models/branches.model.ts
  src/pages/officeSetting/ManagementOfficePage.tsx
Labels: hotfix, A

#181 [A, B]게시판 관련 코드 삭제
  package-lock.json
  package.json
  src/layout/Navigation/Navigation.tsx
  src/layout/Navigation/const/index.ts
  src/layout/Navigation/constants/index.ts
  src/routes/index.tsx
Labels: fix, A, B

#184 [B조] 인사관리 라우트 주석처리
  src/layout/Navigation/constants/index.ts
Labels: fix

#188 [A조] 기본 설정 페이지 급여계산표 페이지 / API
  src/apis/salary-bracket.api.ts
  src/components/BasicSetting/SalaryRange/SalaryRangeCalcRange.tsx
  src/components/BasicSetting/SalaryRange/SalaryRangeCalcResult.tsx
  src/components/BasicSetting/SalaryRange/SalaryRangeHeader.tsx
  src/components/BasicSetting/SalaryRange/SalaryRangeTable.tsx
  src/components/WorkManagement/Commute/CommuteTable.tsx
  src/components/WorkManagement/Work/WorkTable.tsx
  src/components/WorkManagement/Work/WorkTableRows.tsx
  src/components/WorkManagement/WorkHeader.tsx
  src/components/WorkManagement/WorkManagementLayout.tsx
  src/components/WorkManagement/WorkSelect.tsx
  src/constants/queryKeys.ts
  src/constants/salaryRange.ts
  src/hooks/apis/useFetchSalaryRange.ts
  src/hooks/apis/useSalaryBracket.ts
  src/hooks/useSalaryRange.ts
  src/models/officeSetting.model.ts
  src/models/salary-bracket.model.ts
  src/models/salary-range.model.ts
  src/models/salaryRange.model.ts
  src/pages/basicSetting/SalaryRangePage.tsx
  src/pages/officeSetting/ManagementOfficePage.tsx
  src/pages/workManagement/CommuteManagementPage.tsx
  src/utils/calculateInitialValueSalaryRange.ts
  src/utils/calculateSalaryRange.ts
Labels: feat, refactor, A

#192 [C조]-파트타이머 페이지 개발 & 파트타이머 근무내역 / UI
  src/components/OfficeSetting/OfficeSettingCreate.tsx
  src/components/OfficeSetting/OfficeSettingTableCell.tsx
  src/components/WorkManagement/PartTime/CalculationStandard.tsx
  src/components/WorkManagement/PartTime/DetailPartTime.tsx
  src/components/WorkManagement/PartTime/DetailPartTimeDetail.tsx
  src/components/WorkManagement/PartTime/DetailTotalPartTime.tsx
  src/components/WorkManagement/PartTime/PartTime.tsx
  src/components/WorkManagement/PartTime/PartTimeTable.tsx
  src/constants/workManagementTable/workTable.mock.ts
  src/constants/workManagementTable/workTable.ts
  src/hooks/useSalaryRange.ts
  src/models/branches.model.ts
  src/models/work.model.ts
  src/pages/login/Login.tsx
  src/pages/officeSetting/ManagementOfficePage.tsx
  src/pages/workManagement/PartManagementPage.tsx
  src/pages/workManagement/WorkPage.tsx
  src/routes/index.tsx
Labels: feat, style, C

#186 [B조 ]전체O.T내역 / UI
  package-lock.json
  package.json
  src/components/OfficeSetting/OfficeSettingCreate.tsx
  src/components/OfficeSetting/OfficeSettingTableCell.tsx
  src/components/OtManagement/EntireHistory/EntireHistoryFilterbar/EntireHistoryFilterbar.tsx
  src/components/OtManagement/EntireHistory/EntireHistoryFilterbar/WeekSelector.tsx
  src/components/OtManagement/EntireHistory/EntireHistoryHeader.tsx
  src/components/OtManagement/EntireHistory/EntireHistoryTable/EntireHistoryTable.tsx
  src/components/OtManagement/EntireHistory/EntireHistoryTable/EntireHistoryTableRow.tsx
  src/components/OtManagement/OtManagementHeader.tsx
  src/hooks/useSalaryRange.ts
  src/layout/Navigation/Navigation.tsx
  src/layout/Navigation/const/index.ts
  src/layout/Navigation/constants/index.ts
  src/models/branches.model.ts
  src/pages/officeSetting/ManagementOfficePage.tsx
  src/pages/otManagement/EntireHistory/EntireHistoryPage.tsx
  src/routes/index.tsx
Labels: feat, style, B

#194 [C조] 휴무 캘린더 일정 조회 / 등록 / 삭제 API 연동
  src/apis/closed-days.api.ts
  src/components/Common/ChangeMonth.tsx
  src/components/Common/ChangeWeek.tsx
  src/components/Common/Select.tsx
  src/components/HolidayCalendar/EmployeeHolidayRegisterModal.tsx
  src/components/HolidayCalendar/HolidayCalendar.tsx
  src/components/HolidayCalendar/HolidayCalendarHeader.tsx
  src/components/HolidayCalendar/HolidayDeletionPopover.tsx
  src/components/HolidayCalendar/HolidayRegisterPopover.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTableBody.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTableHeader.tsx
  src/components/WorkManagement/Commute/CommuteTable.tsx
  src/components/WorkManagement/Work/WorkTable.tsx
  src/components/WorkManagement/Work/WorkTableRows.tsx
  src/components/WorkManagement/WorkFilter.tsx
  src/components/WorkManagement/WorkHeader.tsx
  src/components/WorkManagement/WorkManagementLayout.tsx
  src/components/WorkManagement/WorkSelect.tsx
  src/constants/queryKeys.ts
  src/hooks/apis/useClosedDays.ts
  src/layout/Navigation/const/index.ts
  src/layout/Navigation/constants/index.ts
  src/models/closedDays.model.ts
  src/models/salarySettlement.model.ts
  src/pages/holidayCalendar/HolidayCalendarPage.tsx
  src/pages/workManagement/CommuteManagementPage.tsx
  src/pages/workManagement/WorkManagementPage.tsx
Labels: feat, style, C

#201 [dev] 배포 방법 변경을 위한 파일 생성
  .github/workflows/deploy.yml
  build.sh
Labels: chore

#204 [C조] 계약서관리 페이지 / UI
  src/components/DocumentManagement/ContractManagement/ContractTable.tsx
  src/components/DocumentManagement/ContractManagement/ContractTableView.tsx
  src/constants/documentManagement/contract.mock.ts
  src/constants/documentManagement/contractTable.ts
  src/models/document.model.ts
  src/pages/documentManagement/ContractManagement.tsx
Labels: feat, style, C

#191 [B조] 연차신청 모달 / UI
  package-lock.json
  package.json
  src/components/DayoffManagement/DayoffManagementHeader.tsx
  src/layout/Navigation/constants/index.ts
Labels: fix, style, B

#211 [C조] 휴무 캘린더의 불필요한 effect 및 refetch 제거
  src/components/HolidayCalendar/HolidayCalendar.tsx
Labels: chore, C

#213 [COMMON] Input 공통 컴포넌트 생성
  src/components/Common/Input.tsx
Labels: feat, common

#217 [C조] 휴무 캘린더 API url 수정, 증명서 관리 페이지 UI 수정
  src/apis/closed-days.api.ts
  src/apis/parts.api.ts
  src/components/Common/Select.tsx
  src/components/DocumentManagement/CertificationManagementList/CertificationManagementItem.tsx
  src/components/DocumentManagement/CertificationManagementList/CertificationManagementTable.tsx
  src/components/DocumentManagement/DocumentManagementHeader.tsx
  src/components/DocumentManagement/DocumentManagementLayout.tsx
  src/components/SalarySettlement/SalaryTable/SalaryTable.tsx
  src/hooks/SalarySettlement/useFilteredEmployees.ts
  src/layout/Navigation/constants/index.ts
  src/pages/documentManagement/HolidayManagement.tsx
  src/pages/documentManagement/TimeoffManagement.tsx
  src/pages/documentManagement/certificationManagement/CertificateManagement.tsx
  src/pages/documentManagement/certificationManagement/constants/index.ts
  src/pages/salarySettlement/SalarySettlementPage.tsx
  src/routes/index.tsx
Labels: feat, style, C

#218 [C조]-근로관리 필터 및 조회 기능 개발
  src/apis/work.api.ts
  src/components/WorkManagement/GenderIcon.tsx
  src/components/WorkManagement/Work/WorkTable.tsx
  src/components/WorkManagement/Work/WorkTableRows.tsx
  src/components/WorkManagement/WorkFilter.tsx
  src/components/WorkManagement/WorkManagementLayout.tsx
  src/components/WorkManagement/WorkSelect.tsx
  src/constants/queryKeys.ts
  src/constants/workManagement/workTable.mock.ts
  src/hooks/apis/useWork.ts
  src/models/work.model.ts
  src/pages/workManagement/PartManagementPage.tsx
  src/pages/workManagement/WorkManagementPage.tsx
Labels: feat, C

#224 [C조] 간편메뉴 Style 수정 및 출근 등록 API 연결
  src/apis/commute.api.ts
  src/constants/queryKeys.ts
  src/hooks/apis/useCommute.ts
  src/pages/simpleMenu/Commute.tsx
  src/pages/simpleMenu/SimpleMenuPage.tsx
Labels: feat, style, C

#220 [C조]-출퇴근/파트타이머 관리 필터 기능 추가
  src/components/WorkManagement/Commute/CommuteTable.tsx
  src/components/WorkManagement/PartTime/PartTimeTable.tsx
  src/components/WorkManagement/Work/WorkTable.tsx
  src/components/WorkManagement/WorkManagementLayout.tsx
  src/constants/workManagement/workTable.mock.ts
  src/models/work.model.ts
Labels: feat, C

#225 [C조] 휴직 관리 페이지 UI 제작
  src/apis/authAxiosInstance.ts
  src/apis/axiosInstance.ts
  src/apis/login.api.ts
  src/components/DocumentManagement/CertificationManagement/CertificationManagementDialog.tsx
  src/components/DocumentManagement/CertificationManagement/CertificationManagementItem.tsx
  src/components/DocumentManagement/CertificationManagement/CertificationManagementTable.tsx
  src/components/DocumentManagement/ContractManagement/ContractTable.tsx
  src/components/DocumentManagement/ContractManagement/ContractTableView.tsx
  src/components/DocumentManagement/DocumentManagementHeader.tsx
  src/components/DocumentManagement/DocumentManagementLayout.tsx
  src/components/DocumentManagement/TimeoffManagement/TimeoffManagementTable.tsx
  src/components/DocumentManagement/TimeoffManagement/TimeoffManagementTableBody.tsx
  src/components/DocumentManagement/TimeoffManagement/TimeoffManagementTableHeader.tsx
  src/components/HolidayCalendar/EmployeeHolidayRegisterModal.tsx
  src/components/HolidayCalendar/HolidayCalendar.tsx
  src/components/HolidayCalendar/HolidayCalendarHeader.tsx
  src/components/HolidayCalendar/HolidayDeletionPopover.tsx
  src/components/HolidayCalendar/HolidayRegisterPopover.tsx
  src/components/WorkManagement/PartTime/CalculationStandard.tsx
  src/constants/documentManagement/timeoffTable.ts
  src/pages/documentManagement/TimeoffManagement.tsx
  src/pages/documentManagement/certificationManagement/CertificateManagement.tsx
Labels: feat, C

#222 [B조] 권한별 조건부렌더링, 필터 URL 반영 작업 일부
  src/components/DayoffManagement/DayoffManagementDetail.tsx
  src/components/DayoffManagement/DayoffManagementFilterbar/DayoffManagementFilterbar.tsx
  src/components/DayoffManagement/DayoffManagementHeader.tsx
  src/hooks/apis/useBranches.ts
  src/hooks/apis/useUserManagement.ts
  src/pages/dayoffManagement/DayoffManagement.tsx
  src/pages/dayoffManagement/approvalHistory/ApprovalHistory.tsx
  tsconfig.tsbuildinfo
Labels: feat, B

#190 [A조] 기본 설정 연차 설정 페이지 UI 및 API 연동
  package-lock.json
  package.json
  src/apis/branches.api.ts
  src/apis/leave-categories.api.ts
  src/apis/leave-policies.api.ts
  src/components/BasicSetting/DayOffSetting/DayOffAutoSetGroups.tsx
  src/components/BasicSetting/DayOffSetting/DayOffSettingForm.tsx
  src/components/BasicSetting/DayOffSetting/DayOffSettingItem.tsx
  src/components/BasicSetting/DayOffSetting/DragContainer.tsx
  src/components/BasicSetting/DayOffSetting/DragItem.tsx
  src/components/BasicSetting/DayOffSetting/PolicyDetails.tsx
  src/components/BasicSetting/DayOffSetting/StrictModeDroppable.tsx
  src/components/BasicSetting/WorkingSetting/SetPart/SetPart.tsx
  src/components/BasicSetting/WorkingSetting/SetPart/SetPartItem.tsx
  src/components/BasicSetting/WorkingSetting/WorkingSettingTitle.tsx
  src/constants/queryKeys.ts
  src/hooks/apis/useBranches.ts
  src/hooks/apis/useLeaveCategories.ts
  src/hooks/apis/useLeavePolicies.ts
  src/hooks/apis/useParts.ts
  src/hooks/useDayOffDrag.tsx
  src/layout/Navigation/constants/index.ts
  src/models/leave-categories.model.ts
  src/models/leave-policies.model.ts
  src/models/workingSetting.model.ts
  src/pages/basicSetting/DayOffPage.tsx
  src/pages/basicSetting/HolidayPage.tsx
  src/pages/basicSetting/WorkingPage.tsx
  src/routes/index.tsx
  src/utils/adaptLeaveRequest.ts
  tsconfig.tsbuildinfo
Labels: feat, A

#227 [B dev] B_dev 작업물 병합
  index.html
  src/apis/user-management.api.ts
  src/components/Common/Select.tsx
  src/components/DayoffManagement/DayoffManagementDetail.tsx
  src/components/DayoffManagement/DayoffManagementFilterbar/DayoffManagementFilterbar.tsx
  src/components/DayoffManagement/DayoffManagementHeader.tsx
  src/components/MemberInfo/MemberBasicInfoTable.tsx
  src/components/MemberInfo/MemberInfoCommon/MemberBasicInfoDatePicker.tsx
  src/components/MemberInfo/MemberInfoCommon/MemberInfoButton.tsx
  src/components/MemberInfo/MemberInfoCommon/MemberInfoInput.tsx
  src/components/MemberInfo/MemberInfoCommon/MemberInfoPopover.tsx
  src/components/MemberInfo/MemberInfoCommon/MemberInfoSelect.tsx
  src/components/MemberInfo/WorkContractTable.tsx
  src/components/MemberManagement/MemberManagementFilterBar.tsx
  src/components/MemberManagement/MemberManagementTable.tsx
  src/constants/queryKeys.ts
  src/hooks/apis/useBranches.ts
  src/hooks/apis/useUserManagement.ts
  src/hooks/useBranchList.ts
  src/hooks/useMemberBasicInfoForm.ts
  src/hooks/usePartList.ts
  src/models/daumPostcode.d.ts
  src/models/user-management.model.ts
  src/models/zipCode.model.ts
  src/pages/dayoffManagement/DayoffManagement.tsx
  src/pages/dayoffManagement/approvalHistory/ApprovalHistory.tsx
  src/pages/memberManagement/MemberManagementPage.tsx
  tsconfig.json
  tsconfig.tsbuildinfo
Labels: feat, B

#226 [C dev] C_dev 작업물 병합
  src/apis/authAxiosInstance.ts
  src/apis/axiosInstance.ts
  src/apis/commute.api.ts
  src/apis/login.api.ts
  src/components/DocumentManagement/CertificationManagement/CertificationManagementDialog.tsx
  src/components/DocumentManagement/CertificationManagement/CertificationManagementItem.tsx
  src/components/DocumentManagement/CertificationManagement/CertificationManagementTable.tsx
  src/components/DocumentManagement/ContractManagement/ContractTable.tsx
  src/components/DocumentManagement/ContractManagement/ContractTableView.tsx
  src/components/DocumentManagement/DocumentManagementHeader.tsx
  src/components/DocumentManagement/DocumentManagementLayout.tsx
  src/components/DocumentManagement/TimeoffManagement/TimeoffManagementTable.tsx
  src/components/DocumentManagement/TimeoffManagement/TimeoffManagementTableBody.tsx
  src/components/DocumentManagement/TimeoffManagement/TimeoffManagementTableHeader.tsx
  src/components/HolidayCalendar/EmployeeHolidayRegisterModal.tsx
  src/components/HolidayCalendar/HolidayCalendar.tsx
  src/components/HolidayCalendar/HolidayCalendarHeader.tsx
  src/components/HolidayCalendar/HolidayDeletionPopover.tsx
  src/components/HolidayCalendar/HolidayRegisterPopover.tsx
  src/components/WorkManagement/Commute/CommuteTable.tsx
  src/components/WorkManagement/PartTime/CalculationStandard.tsx
  src/components/WorkManagement/PartTime/PartTimeTable.tsx
  src/components/WorkManagement/Work/WorkTable.tsx
  src/components/WorkManagement/WorkManagementLayout.tsx
  src/constants/documentManagement/timeoffTable.ts
  src/constants/queryKeys.ts
  src/constants/workManagement/workTable.mock.ts
  src/hooks/apis/useCommute.ts
  src/models/work.model.ts
  src/pages/documentManagement/TimeoffManagement.tsx
  src/pages/documentManagement/certificationManagement/CertificateManagement.tsx
  src/pages/simpleMenu/Commute.tsx
  src/pages/simpleMenu/SimpleMenuPage.tsx
Labels: feat, C

#229 [dev] authAxiosInstnace 추가 및 빌드 에러 해결
  src/apis/authAxiosInstance.ts
  src/apis/login.api.ts
  src/components/DayoffManagement/DayoffManagementFilterbar/DayoffManagementFilterbar.tsx
  src/components/WorkManagement/WorkFilter.tsx
  src/pages/basicSetting/HourlyRangePage.tsx
Labels: hotfix

#233 [A조] 인사기록 관리 UI
  src/components/BasicSetting/HrManagement/HrManagementForm.tsx
  src/components/BasicSetting/HrManagement/HrManagementItem.tsx
  src/layout/Navigation/constants/index.ts
  src/models/hr.model.ts
  src/pages/basicSetting/HrManagementPage.tsx
  src/routes/index.tsx
Labels: feat, A

#231 [A조 dev] 근무 설정 페이지 기능 추가
  src/components/BasicSetting/HrManagement/HrManagementForm.tsx
  src/components/BasicSetting/HrManagement/HrManagementItem.tsx
  src/components/BasicSetting/WorkingSetting/SetPart/SetPart.tsx
  src/components/BasicSetting/WorkingSetting/SetPart/SetPartForm.tsx
  src/hooks/apis/useParts.ts
  src/hooks/apis/useUserManagement.ts
  src/layout/Navigation/constants/index.ts
  src/models/hr.model.ts
  src/models/work-policies.ts
  src/pages/basicSetting/HrManagementPage.tsx
  src/pages/basicSetting/WorkingPage.tsx
  src/routes/index.tsx
  src/utils/adaptPartValue.ts
Labels: feat, A

#240 [FEAT] 임금설정 페이지 - 추가 UI 제작 및 일부 API 연동
  src/apis/branches.api.ts
  src/apis/minimum-wage-policies.api.ts
  src/apis/salary-templates.api.ts
  src/components/BasicSetting/HourlyRange/HourlyRangeSelect.tsx
  src/components/BasicSetting/Wage/WageAutoSettingRow.tsx
  src/components/BasicSetting/Wage/WageCalculateContainer.tsx
  src/components/BasicSetting/Wage/WageContainer.tsx
  src/components/BasicSetting/Wage/WageItem.tsx
  src/components/BasicSetting/Wage/WageList.tsx
  src/components/BasicSetting/Wage/WageListContainer.tsx
  src/components/BasicSetting/Wage/WageMinimumSettingDialog.tsx
  src/components/BasicSetting/Wage/WagePayStatementDialog.tsx
  src/components/BasicSetting/Wage/WagePayStatementField.tsx
  src/components/BasicSetting/Wage/WageSelect.tsx
  src/constants/queryKeys.ts
  src/hooks/apis/useMinimumWagePolices.tsx
  src/hooks/apis/useSalaryTemplates.ts
  src/models/minimum-wage-polices.model.ts
  src/models/salary-templates.model.ts
  src/models/wageSetting.model.ts
  src/pages/basicSetting/WagePage.tsx
Labels: feat, A

#239 [REFACTOR] api 요청 실패 error 처리, 최적화 로직 구현 준비, 비로그인 상태 시 url 직접 접근 제한
  src/apis/authAxiosInstance.ts
  src/apis/axiosInstance.ts
  src/components/BasicSetting/WorkingSetting/SetPart/SetPartForm.tsx
  src/components/DayoffManagement/DayoffManagementFilterbar/DayoffManagementFilterbar.tsx
  src/components/DocumentManagement/DocumentManagementHeader.tsx
  src/components/DocumentManagement/DocumentManagementLayout.tsx
  src/components/HolidayCalendar/HolidayCalendarHeader.tsx
  src/components/Home/PrograssBar.tsx
  src/routes/Notfound.tsx
  src/routes/PrivateRoute.tsx
  src/routes/index.tsx
  vercel.json
  vite.config.ts
Labels: hotfix, refactor

#241 [CHORE] vercel 백엔드 경로 수정
  vercel.json
Labels: chore

#242 [STYLE] 캘린더 페이지 UI 수정
  package-lock.json
  package.json
  src/apis/authAxiosInstance.ts
  src/components/DayoffManagement/DayoffManagementHeader.tsx
  src/components/HolidayCalendar/EmployeeHolidayRegisterModal.tsx
  src/components/HolidayCalendar/HolidayCalendarHeader.tsx
  src/components/HolidayCalendar/HolidayDeletionPopover.tsx
  src/components/HolidayCalendar/HolidayRegisterPopover.tsx
  src/components/MemberInfo/MemberInfoCommon/MemberBasicInfoDatePicker.tsx
  src/components/MemberManagement/MemberManagementTable.tsx
  src/components/MemberManagement/MemberManagementTableCell.tsx
  src/pages/holidayCalendar/HolidayCalendarPage.tsx
  src/pages/login/Login.tsx
  src/pages/memberManagement/MemberManagementPage.tsx
  src/routes/index.tsx
  src/routes/loading.tsx
  tailwind.config.js
Labels: style

#255 [FIX] Fix/#254
  src/components/OfficeSetting/OfficeSettingTable.tsx
  src/hooks/apis/useSalaryTemplates.ts
  src/pages/basicSetting/SalaryRangePage.tsx
Labels: fix, A

#258 시급설정 페이지 기능 추가 / UI 수정
  src/components/BasicSetting/HourlyRange/HourlyRangeContainer.tsx
  src/components/BasicSetting/HourlyRange/HourlyRangeCreate.tsx
  src/components/BasicSetting/HourlyRange/HourlyRangeInputContainer.tsx
  src/components/BasicSetting/HourlyRange/HourlyRangeItem.tsx
  src/components/BasicSetting/HourlyRange/HourlyRangeList.tsx
  src/components/BasicSetting/HourlyRange/HourlyRangeSelect.tsx
  src/components/BasicSetting/Wage/WageContainer.tsx
  src/components/BasicSetting/Wage/WageMinimumSettingDialog.tsx
  src/pages/basicSetting/HourlyRangePage.tsx
  src/pages/basicSetting/WagePage.tsx
Labels: feat, A

#261 feat: 토스트 메시지 구현
  src/App.tsx
  src/apis/axiosInstance.ts
  src/components/BasicSetting/WorkingSetting/SetPart/SetPartItem.tsx
  src/components/Common/Toast/ToastItem.tsx
  src/components/Common/Toast/ToastList.tsx
  src/hooks/apis/useParts.ts
  src/hooks/useToast.ts
  src/store/toastAtoms.ts
  tailwind.config.js
Labels: feat, common

#262 [FEAT] 회원관리-파트/통합관리자 관리 권한변경 모달 제작
  src/components/MemberManagement/SuperManagerSettingModal/SuperManagerSettingCheckboxGroup.tsx
  src/components/MemberManagement/SuperManagerSettingModal/SuperManagerSettingModalContainer.tsx
  src/components/MemberManagement/SuperManagerSettingModal/SuperManagerSettingModalPartVer.tsx
  src/components/MemberManagement/SuperManagerSettingModal/SuperManagerSettingModalSuperVer.tsx
  src/pages/memberManagement/SuperManagerSetting.tsx
Labels: feat, B
